Value resolver
zenstruck/filesystem pull request #95
Opened 2023-03-02 12:34 UTC by Lustmored

This is extraction of value resolver from #91, without anything new and fancy :smile_cat:

2023-03-02 16:29 UTC, kbond commented on tests/Filesystem/Symfony/HttpKernel/RequestFilesExtractorTest.php
> +class RequestFilesExtractorTest extends TestCase
Like you did in https://github.com/kbond/document-library/pull/4, I think it'll be valuable to have functional tests for this.

2023-03-02 16:41 UTC, kbond commented
Furthering on my comments from #91, 7ca93485e7f6eb869087aab019d3978d792943e7 adds an important feature. Previously, only when persisting `PendingFile`'s to you db, did they have their path generated. Now, any `File` that's persisted that does not match the mapped property's filesystem is saved in the same way.

What this potentially allows is:

```php
public function updateProfileImage(
    User $user,
    EntityManagerInterface $em,

    #[UploadedFile(
        filesystem: 'temp'
        constraints: new ImageConstraint(maxWidth: 500, maxHeight: 500),
        errorStatus: 422, // this would be the default
    )]
    Image $image,
): Response {
    $user->setProfileImage($image);
    $em->flush();

    return new Response(...);
}
```

In the above specific scenario, it's probably better to use a `PendingFile` (a not save to the `temp` filesystem) but I'm thinking about live components where you'd want the file saved to a temporary filesystem to be able to pass back to the component (if some other field's validation failed).

2023-03-03 10:22 UTC, Lustmored commented on tests/Filesystem/Symfony/HttpKernel/RequestFilesExtractorTest.php
> +class RequestFilesExtractorTest extends TestCase
Good catch! I've totally missed it. I'm pushing imported tests right now and will follow with extending for images :+1:

2023-03-03 12:57 UTC, Lustmored commented
@kbond Nice! Mentioned features makes most of my other PR pretty obsolete, so let's leave it aside for now.

I have tweaked and empowered value resolver quite a bit. Code is better organized in my opinion and is easier to extend. I have left storing to filesystem for now as I need to wrap my head around it. But the validation logic is now in place (it throws `HttpException` on failure).

Unfortunately the syntax for constraints in attributes is only available from PHP 8.1 forward ( https://www.php.net/releases/8.1/en.php#new_in_initializers ). I can try to skip some tests on PHP 8.0 or we can bump required PHP version (that'd be on par with Symfony 6.1+) - I leave the decision to you.

The problems I see with storing files to filesystems:
- I would prefer to store them on serialization, not initialization to not waste resources on files that'll be handled within a single request,
- I don't see a way to allow controller (mainly component) get the list of violations. Maybe in such a case the validation should be skipped altogether and done entirely on controller side.

Also I think it could be useful to have own `HttpException` for this case, so that it is possible to configure logging of it on a framework (see tests - right now they log errors during validation testing).

All in all it needs a bit more love, but is shaping nicely.

2023-03-03 13:12 UTC, Lustmored commented
I think I have a take on this "store on serialization" concept. How about going this way:

Create a `SerializablePendingFile` class that would extend `PendingFile` and accept an additional parameter in constructor - a closure `Closure(PendingFile $file): File` that can be used to store file to a filesystem. An additional method (like `save(): File`) just calls the closure and returns the resulting file.

- If no serialization occurs - lifecycle of the object remains the same as usual, no side effects.
- The serialization of `SerializablePendingFile` is possible and it simply calls the closure first and then serializes the resulting file.

Creating such a closure in a value resolver phase is as simple as storing file (in fact it's the same logic, but wrapped in a closure).

(same for `PendingImage`)

What do you think of such approach?

2023-03-03 14:08 UTC, kbond commented
What about allowing pendingfile to be lazy? Then we can wrap in in a serializedfile if you want to serialize it?

2023-03-03 14:13 UTC, Lustmored commented
Wouldn't that store the file on access and not serialization? I admit I didn't analyze `LazyNode`/`SerializableFile` enough to answer that. Could you craft a code stub of how would that work?

2023-03-03 14:49 UTC, kbond reviewed
> Also I think it could be useful to have own HttpException for this case, so that it is possible to configure logging of it on a framework (see tests - right now they log errors during validation testing).

This is because throwing the HttpException generates logs?

I think we should leave it up to the user - they can configure this behaviour in framework/monolog config IIRC.

I've handled the test output in a few other libraries by setting a null logger: https://github.com/zenstruck/browser/blob/e46f25ae96f8a6b67ce2f547f6d4e6b24398a9a8/tests/Fixture/Kernel.php#L205

2023-03-03 14:49 UTC, kbond commented on src/Filesystem/Attribute/UploadedFile.php
> +        public ?int $errorStatus = null,
Let's set the default as 422 so it's obvious to the end user what the default is.

2023-03-03 14:49 UTC, kbond commented on src/Filesystem/Attribute/UploadedFile.php
> +        public ?bool $multiple = null,
These two properties are unfortunate... But there isn't a way to detect that the array expects...

In the future, it could be useful to have a FileCollection/ImageCollection then we could deprecate these properties.

For now, can you move them to the end of the list?

2023-03-03 14:49 UTC, kbond commented on tests/Fixtures/TestKernel.php
> +        $routes->import(__DIR__.'/Controller', 'annotation');
This can be `attribute` now I think.

2023-03-03 14:49 UTC, kbond commented on tests/Fixtures/Controller/ArgumentResolverController.php
> +    #[Route('/validated-file', name: 'validated-file')]
Does moving this action to another file and only calling the route on php8.1+ fix the php8.0 problem?

I'm find keeping the min version php8.0 and not letting users add custom constraints. They'd still get the basic ones.

2023-03-03 14:58 UTC, kbond commented
> I think I have a take on this "store on serialization" concept. How about going this way:

I'm having a hard time understanding what you'd like to achieve with "store on serialization". Is it related to live components or another use-case?

I've been thinking about the lifecycle of a `File`/`Image` property on a live component:
1. User uploads file for this property
2. We always store to a _temp_ filesystem
3. Validate
4. Regardless of validation failure, make the file available in the live twig template (so they can get the public/transform url)
5. Send the live response back (serializing the file as normal)

2023-03-03 15:16 UTC, Lustmored commented
Thanks for the review! Regarding the serialization...

> 4\. Regardless of validation failure, make the file available in the live twig template (so they can get the public/transform url)

Well, I completely forgot about this one when crafting the solution. Thank you for pointing this out, I admit to being wrong 👍 With that settled I think I will be able to finalize the PR next week without all this "store on serialize" madness 😸

2023-03-03 15:48 UTC, kbond commented on tests/Filesystem/Symfony/HttpKernel/RequestFilesExtractorTest.php
> +            __DIR__.'/../../../Fixtures/files/textfile.txt',
```suggestion
            fixture('textfile.txt'),
```

2023-03-03 17:01 UTC, kbond commented on src/Filesystem/Attribute/UploadedFile.php
> +        public ?bool $multiple = null,
If `multiple` exists purely for the case where a type-hint isn't provided, I say drop it - typehints are required! 🤣

2023-03-03 17:06 UTC, kbond commented
> Well, I completely forgot about this one when crafting the solution. 

Ok, glad we're on the same page now!

It can wait for a later PR but the reason I was thinking of adding `filesystem`/`namer` properties to `UploadedFile` is so it could perhaps be used directly by live-components (we'd need to change the attribute to be allowed on properties of course).

2023-03-03 17:20 UTC, Lustmored commented
> It can wait for a later PR but the reason I was thinking of adding `filesystem`/`namer` properties to `UploadedFile` is so it could perhaps be used directly by live-components (we'd need to change the attribute to be allowed on properties of course).

Sure, they will be very simple to provide when we want to store file as soon as possible instead of as late as possible. I will add them :+1:

2023-03-03 21:31 UTC, kbond commented
Thinking we should have both `UploadedFile` and `PendingUploadedFile` to avoid one attribute from doing too much, wdyt?

2023-03-14 14:16 UTC, Lustmored commented
I think I have done everything (but maybe more tests and docs obviously). I have indeed created separate attributes for pending file and stored one, so that distinction is obvious.

> This is because throwing the HttpException generates logs?
> 
> I think we should leave it up to the user - they can configure this behaviour in framework/monolog config IIRC.

I have finally decided to add custom exception class. This is to actually allow configuring it's severity and on framework level. The config there is keyed by an exception class, so using `HttpException` would make it impossible to handle in separation of other `HttpException`s.

I also added the property to attributes. I'm unsure if that's required by live components (I need to catch up with live components development soon), but doesn't hurt to have it in place. When we'll have this one settled I'll jump back in to UX to see what happened in recent months. I think file uploads are still unhandled. If that's the case I'll start with frontend code only in hope that it'll be enough to use this library. Anything more will be added value :tada:

2023-03-17 14:33 UTC, kbond reviewed
Really liking this - I can use this in my app right away!

> I have finally decided to add custom exception class.

This is a good call. To clarify, by default, it will throw a 422 but you can adjust your framework config to intercept/adjust?

2023-03-17 14:33 UTC, kbond commented on phpstan.neon
> +    checkGenericClassInNonGenericObjectType: false
Why's this needed? I'd prefer to inline `@phpstan-ignore-line` if we can't fix.

2023-03-17 14:33 UTC, kbond commented on src/Filesystem/Attribute/PendingUploadedFile.php
> + * @author Jakub Caban <kuba.iluvatar@gmail.com>
```suggestion
 * @author Jakub Caban <kuba.iluvatar@gmail.com>
 *
 * @readonly
```

2023-03-17 14:33 UTC, kbond commented on src/Filesystem/Attribute/UploadedFile.php
> + * @author Jakub Caban <kuba.iluvatar@gmail.com>
```suggestion
 * @author Jakub Caban <kuba.iluvatar@gmail.com>
 *
 * @readonly
```

2023-03-17 14:33 UTC, kbond commented on src/Filesystem/Attribute/UploadedFile.php
> +        $this->namer = $namer ?? new Expression('{checksum}/{name}{ext}');
```suggestion
        $this->namer = $namer ?? new Expression('{checksum}-{name}{ext}');
```

To avoid tons of extra sub-directories by default.

2023-03-17 14:33 UTC, kbond commented on src/Filesystem/Symfony/HttpKernel/RequestFilesExtractor.php
> + * @author Jakub Caban <kuba.iluvatar@gmail.com>
```suggestion
 * @author Jakub Caban <kuba.iluvatar@gmail.com>
 *
 * @internal
```

2023-03-17 14:33 UTC, kbond commented on src/Filesystem/Exception/IncorrectFileHttpException.php
> +namespace Zenstruck\Filesystem\Exception;
```suggestion
namespace Zenstruck\Filesystem\Symfony\Exception;
```

2023-04-06 13:39 UTC, kbond commented on src/Filesystem/Attribute/UploadedFile.php
> +        $this->namer = $namer ?? new Expression('{checksum}/{name}{ext}');
Hmm, yeah, that's a good point. We do have the `zenstruck:filesystem:purge` which has an option to remove empty directories. (this could be scheduled to run daily or whatever).

Let's leave as is.

2023-04-06 13:45 UTC, kbond requested changes
Just a few last minor things, then let's merge!

2023-04-06 13:45 UTC, kbond commented on src/Filesystem/Attribute/PendingUploadedFile.php
> +    public static function forArgument(ArgumentMetadata $argument): self
```suggestion
    /**
     * @internal
     */
    public static function forArgument(ArgumentMetadata $argument): self
```

2023-04-06 13:45 UTC, kbond commented on src/Filesystem/Attribute/PendingUploadedFile.php
> +            $attribute = new self();
```suggestion
            $attribute = new static();
```
?

2023-04-07 11:59 UTC, Lustmored commented
> Just a few last minor things, then let's merge!

Both are commited and phpstan is made happy :smile:

2023-04-07 12:19 UTC, kbond approved these changes
Awesome, thanks Jakub!

2023-04-07 12:19 UTC, merged